### ISSUE TITLE
Erlang error: :badmatch

### ISSUE THREAD

**Issue by axelson** [appsignal/appsignal-elixir#393] opened 2018-08-23 23:09 UTC
I'm receiving this error in production from within the Appsignal code at a location that I would not expect:

```Full Backtrace
Erlang error: :badmatch
unknown  ? exception/1
unknown:?:in `exception/1'
error_handler.ex  133 extract_reason_and_message/2
lib/appsignal/error_handler.ex:133:in `extract_reason_and_message/2'
error_handler.ex  87 match_error_report/2
lib/appsignal/error_handler.ex:87:in `match_error_report/2'
error_handler.ex  32 handle_event/2
lib/appsignal/error_handler.ex:32:in `handle_event/2'
gen_event.erl  573 server_update/4
gen_event.erl:573:in `server_update/4'
gen_event.erl  555 server_notify/4
gen_event.erl:555:in `server_notify/4'
gen_event.erl  557 server_notify/4
gen_event.erl:557:in `server_notify/4'
gen_event.erl  296 handle_msg/6
gen_event.erl:296:in `handle_msg/6'
```

I'm not sure about the data that is causing the error.

**Comment by jeffkreeftmeijer** [comment] 2018-08-27 10:02
Hey @axelson! :wave:

Thanks for letting us know about this. It looks like our `ErrorHandler` stubles on a `:badmatch`, but we only handle `UndefinedFunctionError`s in `extract_reason_and_message`.

I've pushed which [removes this constraint](https://github.com/appsignal/appsignal-elixir/blob/27d2db0ff76c633145e988530c1a7fdff910a80c/lib/appsignal/error_handler.ex#L135) a fix to the `badmatch-in-extract` branch. Could you try switching to that and triggering the error again, to see if that fixes this issue for you? I'm curious to know what's being reported in AppSignal, so we can find out what's the source of this error.

**Comment by tombruijn** [comment] 2018-09-07 11:56
Hey @axelson,

We've not been able to confirm your issue. We can't apply the fix without reproducing it. It would be great if you could let us know if the fix worked and how this issue occurred in your setup.

Closing the issue for now. 
Please comment or reopen the issue to update us!

**Closed** 2018-09-07 11:56 UTC
Labels: support
