### ISSUE TITLE
`:erlang.apply` on the config

### ISSUE THREAD

**Issue by mjquinlan2000** [appsignal/appsignal-elixir#494] opened 2019-06-07 18:59 UTC
Hello,

I have been getting an error on ~> 1.10 intermittently.

It looks like the library is trying to run 

```elixir
:erlang.apply([name: "[REDACTED]", push_api_key: "[REDACTED]", env: "dev", revision: "19eb681d58f055c70f385c7239be30888a350d8d", active: true], :valid, [])
```

Which of course throws this error `Evaluation failed with: argument error`. 

Here's the stack trace:

![image](https://user-images.githubusercontent.com/1171608/59127017-ba104580-8923-11e9-96ea-485745eca9cc.png)

I can't reliably reproduce it and it's happening during CI builds. The problem goes away when I downgrade to 1.9.4. Any help would be greatly appreciated.

**Comment by lackac** [comment] 2019-06-11 12:40
I believe running ecto migrations with `--log-sql` is a reliable way to reproduce the issue. The problem seems to be that the `appsignal` application is not started in this case so the initialization process has no chance of updating the app environment and putting a map in place of the keyword list.

**Comment by mjquinlan2000** [comment] 2019-06-11 14:49
@lackac that makes a lot of sense. It's happening on my pre-release tasks on CI and I'm not starting the appsignal application with the rest of the apps I bring up to run migrations. However, this still seems to be a regression due to the fact that it does not happen on 1.9.x

**Comment by jvanbaarsen** [comment] 2019-06-14 09:54
Hi,

I've looked at this issue together with @jeffkreeftmeijer, and we aren't able to reproduce this yet.

We retraced all the steps that the app is taking to convert your configuration into something that AppSignal understand.

When you give us the config via `config :appsignal, :config,...` you actually set it as a list, internally we convert this to a map because erlangs `apply` method can only deal with that data type.

It seems that somewhere this conversion is skipped, and we have trouble pinpointing where that would be.

The only way we can reproduce this issue is when we change `Config.initialize()` to an atom `:ok` in this file: https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal.ex#L84/

Can you tell me a bit more about your setup? Specifically the following:
- How do you set your config? (Make sure not to post sensitive data in this thread)
- What version of Phoenix / Elixir are you using?
- Do you configure :applications or :extra_applications in your mix.exs file?

**Comment by lackac** [comment] 2019-06-14 10:46
Versions:

- Elixir `1.8.1`
- OTP `21.2.5`
- Ecto `2.2.12`
- we're not using Phoenix

We're setting the config from `config/config.exs` for everything except the push api key, which comes from the `APPSIGNAL_PUSH_API_KEY` environment variable.

We have `:extra_applications` set to `[:logger, :appsignal]`.

**Comment by mjquinlan2000** [comment] 2019-06-18 21:21
Sorry for the late response guys. Here's the info from my project

Versions:

* Erlang 21.3.8.3
* Elixir 1.8.2
* Ecto 3.1.4
* Phoenix 1.4.6

Extra applications:

```elixir
      extra_applications: [
        :logger,
        :runtime_tools,
        :httpoison,
        :ecto_sql,
        :shards
      ]
```

Config:

```elixir
config :appsignal, :config,
  push_api_key: "[REDACTED]",
  env: "prod",
  revision: "[CURRENT_GIT_SHA]",
  active: true
```

**Comment by mjquinlan2000** [comment] 2019-06-20 21:24
I tried putting `:appsignal` in the `extra_applications: [...]` and it did not help

**Comment by seamon** [comment] 2019-06-24 10:06
we have the same error.

whenever we use `upgrade` to run the hot swapping, some `gen_server` will throw exception just like this:

```
2019-06-24 17:32:41.542 [error] GenServer XXXXXX terminating
** (ArgumentError) argument error
    :erlang.apply([name: "XXX", env: :XXX, revision: "119.20624.3093151", skip_session_data: true, active: true, push_api_key: "XXX-XXX-XXX"], :valid, [])
    (appsignal) lib/appsignal/config.ex:94: Appsignal.Config.active?/0
    (appsignal) lib/appsignal/transaction/registry.ex:52: Appsignal.TransactionRegistry.lookup/1
    (appsignal) lib/appsignal/transaction.ex:166: Appsignal.Transaction.record_event/5
    (appsignal) lib/appsignal/ecto.ex:56: Appsignal.Ecto.log/1
    (chaince) XXXXX.Repo.__log__/1
    (db_connection) lib/db_connection.ex:1186: DBConnection.log/6
    (ecto) lib/ecto/adapters/postgres/connection.ex:98: Ecto.Adapters.Postgres.Connection.execute/4
Last message: :XXX
```

either adding `extra_applications: [:appsignal]`, or `{:ok, _} = Application.ensure_all_started(:appsignal)`, nothing changed

but when we removed `Appsignal.Ecto` from `config :xxx, xxx.Repo, loggers: [Appsignal.Ecto, Ecto.LogEntry]`, the errors disappeared

```
elixir: 1.8.2
OTP: 22 (erts-10.4.2)
phoenix: 1.4.8
ecto: 2.2.12
appsignal: 1.10.7
```

hope it helps, thank you

**Comment by jeffkreeftmeijer** [comment] 2019-06-24 10:33
Hey @mjquinlan2000, @lackac and @seamon,

Thanks for reporting this issue, and bearing with us as we find what’s causing it. Also, thanks for your input so far, it’s certainly guiding us in the right direction. Here’s what I have so far:

We started explicitly checking if the integration was configured before adding or fetching a Transaction from the Registry in https://github.com/appsignal/appsignal-elixir/pull/480/files, which was releases in 1.10.5.

In this case, the configuration isn’t loaded. The call to `Config.active?/0`  so the call to check the configuration failed. [This patch](https://github.com/appsignal/appsignal-elixir/commit/40f4e34cb1a2ff75f1d5d2dbb8c6c904966083cb) makes sure to catch that case, so the function returns `false` if the configuration is anything but a map with both its `:active` and `:valid` keys containing true.

However, a case like this shouldn’t normally happen, as the AppSignal integration isn’t loaded, and shouldn’t try to create a Transaction here. It sounds like @seamon is on to something here, but adding `AppSignal.Ecto` as a logger didn’t reproduce the problem in my example application when running migrations with `--log-sql`.

So, some more questions to help me get to the bottom of this;

1. Could you check to make sure you have not configured `Appsignal.Ecto` as a logger in the `Ecto` configuration, but use the Telemetry hook instead?
2. Could you try the patch in the `config-active-keyword` branch locally, to see if that resolves the issue for you?
3. Could you send me the whole stack trace of this error, if you’re able to reproduce this locally?

Thanks for your help so far!

**Comment by mjquinlan2000** [comment] 2019-06-24 15:09
I will get around to it later today after I finish up some meetings.

**Comment by seamon** [comment] 2019-06-25 02:18
@jeffkreeftmeijer 

1. yes, we configured `Appsignal.Ecto` in `config :xxx, xxx.Repo, loggers: [Appsignal.Ecto, Ecto.LogEntry]`, not in the telemetry hook

2. yes, this patch resolved the problem when we run hot code swapping just like before

3. the whole stack trace posted above.

thanks for your work !

**Comment by jeffkreeftmeijer** [comment] 2019-06-25 09:20
@seamon Thanks for getting back to me on this! Did you switch to the telemetry hook now?

We'll do some internal testing, and we'll publish the patch in the `config-active-keyword` as a patch release. We'll keep you posted!

**Comment by seamon** [comment] 2019-06-25 09:30
@jeffkreeftmeijer unfortunately, we're using ecto 2, so :telemetry.attach can't be used for logger. sorry

**Comment by jeffkreeftmeijer** [comment] 2019-06-27 09:45
Hey all! We've just released version 1.10.8 of the AppSignal Elixir integration, which should resolve the issue while running migrations in Ecto 2.x applications. Please upgrade to that to see if that resolves your issues. I'm closing this issue, but feel free to reopen it if you're still running into this after upgrading.

**Closed by jeffkreeftmeijer** 2019-06-27 09:45 UTC
Labels: bug

**Comment by mjquinlan2000** [comment] 2019-06-27 16:28
I just updated to 1.10.8 and did a test deploy and it works. Thank you for the quick action on this!

**Comment by jeffkreeftmeijer** [comment] 2019-06-28 08:07
That's great to hear! Thanks for letting us know about this, and please reach out if you run into anything else.
