### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by ospaarmann** [appsignal/appsignal-elixir#16] opened 2016-10-06 14:29 UTC
Hey,

I’m trying out the Beta of AppSignal for Elixir and ran into an issue when using building the Docker image that I use to ship the app. It looks to me that the download of the AppSignal agent causes the problem. Maybe downloading the agent after compilation isn’t the best approach…

Anyway, here is my log dump (or part of it). Would be great if you could look into this.

Thanks

```
Compiling 1 file (.ex)
Generated uuid app
==> mime
Compiling 1 file (.ex)
Generated mime app
==> plug
Compiling 44 files (.ex)
Generated plug app
==> cors_plug
Compiling 1 file (.ex)
Generated cors_plug app
==> phoenix_html
Compiling 8 files (.ex)
Generated phoenix_html app
==> exrm
Compiling 11 files (.ex)
warning: function beam_imports/1 is unused
  lib/exrm/appups.ex:98

warning: variable v2_file is unused
  lib/exrm/appups.ex:84

Generated exrm app
==> phoenix
Compiling 60 files (.ex)
Generated phoenix app
==> appsignal
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (FunctionClauseError) no function clause matching in Mix.Appsignal.Helper.map_arch/1
    mix_helpers.exs:88: Mix.Appsignal.Helper.map_arch('x86_64-alpine-linux-musl')
    mix_helpers.exs:13: Mix.Appsignal.Helper.ensure_downloaded/0
    mix.exs:6: Mix.Tasks.Compile.Appsignal.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3

The command '/bin/sh -c mix compile' returned a non-zero code: 1
```

**Comment by arjan** [comment] 2016-10-06 20:26
Hi, thanks for your report. I can add the missing arch (`x86_64-alpine-linux-musl`) to the mapping in the helper. 

However there's an underlying issue that the appsignal agent currently does not work with Alpine linux due to its dependency on musl. We're working on this, but can't give an ETA just yet unfortunately.

**Comment by arjan** [comment] 2016-10-07 06:52
See [this commit](https://github.com/Ahamtech/appsignal-elixir/commit/989ea524ef7141b2b91a54232605266a35809118) on how to add it to the mapping. However, YMMV with alpine..

**Comment by ospaarmann** [comment] 2016-10-07 09:59
Thank you for the feedback. Alpine is great for Docker containers because it is extremely lean (only roughly 6 MB for the image), has good additional security and a stable release model. So it would be great if you could support Alpine, especially since it is so popular in the Docker community.

**Comment by arjan** [comment] 2016-10-07 11:05
I know; this has to do with the Appsignal agent being coded in Rust, and [this issue](https://github.com/rust-lang/rust/issues/37007#issuecomment-252119351) prevents this.

**Comment by teamon** [comment] 2016-11-14 18:40
Have you tried compiling for musl now that https://github.com/rust-lang/rfcs/pull/1721 is merged? (I just went from "hooooray phoenix monitoring that just works" into complete sadness because of this issue, so if there is anything I could try to make it work please let me know)

**Comment by arjan** [comment] 2016-11-14 19:49
Thanks for the headsup. @thijsc is the Rust guy, he'll fill you in.

**Comment by thijsc** [comment] 2016-11-15 09:31
We're keeping close track of this. The RFC was merged, the actual implementation work is tracked in https://github.com/rust-lang/rust/issues/37406. As soon as this pull has been merged we're going to work on this again.

**Comment by tombruijn** [comment] 2016-12-21 15:52
I've been working on a very experimental Alpine Linux supported build of our agent and extension. Today I got a working build and tested it. It worked 🎉 

From now on I'll be working on updating our build process to be able to ship a official alpha release.

Ping us at support@appsignal.com if you want to be in the first alpha beta users batch

**Comment by tombruijn** [comment] 2017-01-17 13:29
Good news everyone! Version `0.11.0` was just released adding Alpine Linux support for AppSignal for Elixir.

No extra steps are needed for installation.

Try it out and let us know if you run into any problems!

**Comment by arjan** [comment] 2017-01-17 13:52
Should we close this ticket? Or are we waiting on confirmation from @ospaarmann or @jeroenvisser101 ?

**Comment by jeroenvisser101** [comment] 2017-01-17 13:59
You can close it, I already confirmed it was working by running my fork yesterday 👍

**Closed** 2017-01-17 14:09 UTC
