### ISSUE TITLE
Question: Deleting Closed Spans

### ISSUE THREAD

**Issue by aj-foster** [appsignal/appsignal-elixir#769] opened 2022-04-28 21:50 UTC
Hello there 👋🏼 

We use AppSignal to instrument a few operations that happen **a lot** — much more often than we want to report to the service. For these operations, we've taken the stance of reporting errors only. So far, we've attempted to accomplish this with the following workflow:

1. Open a span (`Tracer.create_span/2`) with a parent when appropriate
2. Perform the action, including function calls that create additional spans (for example, queries)
3. If the action was successful, close the span (`Tracer.close_span/1`) and immediately delete all spans for the current process (`Tracer.delete(self())`)
4. If the action was not successful, add error data and close the span without deletion.

This seems to work for the top-level span, but we still find that some of the sub-spans (for example, queries performed during the operation) are still reported to AppSignal. You can't find them in the UI at all except in throughput graphs and total event counts — presumably because the well-named parent spans were deleted. 

Is this intentional? We have verified that the reported events have spans in the same process as the caller, and we are successfully deleting the parent spans. Is it a matter of timing, or the Nif acting in a way we don't expect?

Thanks for your help!

**Comment by tombruijn** [comment] 2022-05-02 11:20
Hi @aj-foster, I understand what you're trying to do, but removing spans from the Tracer doesn't remove them entirely. Once a trace is created, it's created and will most likely be sent at some point in the process. Whenever a span is closed it will transmitted to AppSignal, even if its root span is not (yet) closed. This may result in what you're seeing as we always create metrics for these spans even if the span details are not visible.

We're not support error only reporting this way. Our goal is to offer a one solution product for all the different useful metrics we can extract from an app. When a feature is disabled partially or entirely we can't reliably combine metrics of these features anymore. This prevents us from providing a complete overview of what's happening in apps and makes it more difficult to find the root cause of an issue.

What I can suggest you try to do, is remove the default instrumentation, the instrumentation you currently rely on, or any instrumentation you added. Then use the [`send_error` function](https://docs.appsignal.com/elixir/instrumentation/exception-handling.html#appsignal-send_error-3) to only report errors for these actions.

Let me know if that made things more clear and if it helped :)

**Closed by tombruijn** 2022-05-02 11:20 UTC
Labels: support
