### ISSUE TITLE
Allow setting per-process metadata to unhandled exceptions

### ISSUE THREAD

**Issue by 1player** [appsignal/appsignal-elixir#925] opened 2024-03-04 12:10 UTC
Following the conversation with support about #252 and GenServer support, one of the major pain points right now is the inability to add metadata to the root span that is then sent along when this library catches an unhandled exceptions.

Here's a very simple example:

```
defmodule SomeServer do
  use GenServer

  def init(_) do
    state = %{}

    # What should I do here to add some metadata to the unhandled exception below?
    # This does not work:
    # Appsignal.Tracer.root_span() |> Appsignal.Span.set_attribute("process_name", derive_name_from_state(state))

    {:ok, state, {:continue, :next}}
  end

  def handle_continue(:next, _state) do
    raise "bug!"
  end
end
```

The suggestion I got was to wrap the exception in Appsignal.instrument or a try/catch block using Appsignal.set_error, but this is not really ideal for multiple reasons:

- I want to have metadata for exceptions I do not yet know about, i.e. bugs. I cannot wrap a call that raises if I don't know there's a bug in the first place
- Wrapping everything in Appsignal.instrument to know what is causing a bug adds a lot of visual noise
- It is not idiomatic Elixir. Having processes that crash is perfectly fine in this platform, so I only add try/catch blocks when I want to *ignore* an exception. Adding a try/catch block around actual bugs flies completely against this best practice.

You already are associating spans with processes, but following the discussion with support, I still do not understand why the default error handler at  https://github.com/appsignal/appsignal-elixir/blob/main/lib/appsignal/error/backend.ex does not inherit from the root span (that should be associated with the current pid `self()`).

**Comment by unflxw** [comment] 2024-03-04 15:32
Hi @1player,

As discussed over support, the way that the AppSignal model of spans and traces works means that it is not possible to do what you describe. Furthermore, the Elixir error backend is something that we would like to deprecate going forward, in favor of framework-specific instrumentations, due to the issues you describe.

In AppSignal, an error belongs to a trace, which is defined by its root span, and that trace is not sent to AppSignal until it is closed. Spans are not something you "inherit" from, or where you set background information for future errors. Spans represent events that take place in your application, within a broader trace that represents a response/request cycle.

If you create a trace on `init/1` for your current process, that trace will currently never be closed. The error backend uses its own traces.

If the error backend used the existing `init/1` trace, then that error would never be sent, as that trace will never be closed.

If the error backend used the existing `init/1` trace and closed it, then the context information that you added would only apply to the first span for which it is reported. Future usages of the error backend would find no active span in that process, as the trace has been closed, and report the information without context.

**Closed by unflxw** 2024-03-04 15:32 UTC
Labels: support

**Comment by 1player** [comment] 2024-03-04 16:37
Sad to see this closed without chance of further discussion. 

If traces are incompatible with this request, I do not think it is unthinkable to have a separate API that stored metadata in the process dictionary that can later be attached to the exception, without involving the current design of spans. 

As I said in our email conversation, not being able to have some metadata when debugging GenServers make this library less useful than it has a right to be. I hoped we could find a middle ground rather than just shutting down entirely this very valid use-case but alas...

It honestly doesn't feel great having to keep requiring one of your competitors for error handling because I cannot attach a piece of data to a process.

**Comment by unflxw** [comment] 2024-03-04 17:18
As you can see, there is a chance of further discussion -- you are engaging on it, comments are not closed. The issue is, however, closed, in the sense that we do not intend to implement this.

I took a look at the implementation for the error backend before closing this, and discussed its implementation with @jeffkreeftmeijer, who initially implemented it. Long story short, the first issue we encounter is that the error backend is itself run [as a separate process](https://github.com/elixir-lang/elixir/blob/14c0b30101bf01a7f34a8903b863f3c17ce4c8da/lib/logger/lib/logger/backends/internal.ex#L66-L80), so it is not privy to the context of the process in which the error took place.

There is [an attempt](https://github.com/appsignal/appsignal-elixir/blob/main/lib/appsignal/error/backend.ex#L43-L45) to fetch that data anyway from the processes' tracer context (this is why we store it in an ETS instead of merely as process metadata!) and add it to the ongoing trace, but tragically, in practice, the trace is already closed, and therefore lost, by the time that the error backend executes.

We could consider some per-process background metadata that the error backend could fallback to if (as it almost always happens) it fails to attach the error to its original trace. But we'd rather invest our efforts, if possible, in providing a genuinely compelling GenServer instrumentation, rather than on adding opt-in patches to the catch-all, technically-better-than-nothing error reporting system that the error backend.

Furthermore, the error backend is an Elixir logger backend, and these are themselves [deprecated in Elixir](https://hexdocs.pm/logger/main/Logger.html#add_backend/2) as a whole. Rather than investing our efforts in patching up a sub-par system, we'd rather expand _proper instrumentation_ to more areas of our customers' applications.
