### ISSUE TITLE
Appsignal.Error.metadata/2 crashing for gen_server timeout

### ISSUE THREAD

**Issue by davidjohnmaccallum** [appsignal/appsignal-elixir#850] opened 2023-06-05 19:42 UTC
## Describe the bug

I have a phoenix app that does some memory intensive processing. I added poolboy so that I would create a pool of worker processes that would queue when things get busy. I have a timeout set on the checkout function of the worker pool. When the checkout function times out the appsignal error reporter crashes with the following error:

```
[error] #PID<0.3296.0> running PrivySealSealsWeb.Endpoint (connection #PID<0.3217.0>, stream id 2) terminated
Server: localhost:4003 (http)
Request: GET /f7d1e4dd-6064-4495-9de1-368922928902
** (exit) exited in: :gen_server.call(:image_magick_pool, {:checkout, #Reference<0.302945953.2507669506.73455>, true}, 5000)
    ** (EXIT) time out
[error] :gen_event handler Appsignal.Error.Backend installed in Logger terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:gen_server, :call, [:image_magick_pool, {:checkout, #Reference<0.302945953.2507669506.73455>, true}, 5000]} of type Tuple. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, OPQ.Queue, Postgrex.Stream, Range, Scrivener.Page, Stream, Timex.Interval
    (elixir 1.14.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.14.3) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.14.3) lib/enum.ex:4307: Enum.map/2
    (appsignal 2.7.2) lib/appsignal/error.ex:7: Appsignal.Error.metadata/2
    (appsignal 2.7.2) lib/appsignal/span.ex:244: Appsignal.Span.add_error/4
    (appsignal 2.7.2) lib/appsignal/error/backend.ex:97: Appsignal.Error.Backend.set_error_data/3
    (appsignal 2.7.2) lib/appsignal/error/backend.ex:30: Appsignal.Error.Backend.handle_event/2
    (stdlib 4.3) gen_event.erl:802: :gen_event.server_update/4
    (stdlib 4.3) gen_event.erl:784: :gen_event.server_notify/4
    (stdlib 4.3) gen_event.erl:526: :gen_event.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:error, #PID<0.776.0>, {Logger, ["#PID<0.3296.0>", " running ", "PrivySealSealsWeb.Endpoint", [" (connection ", "#PID<0.3217.0>", ", stream id ", "2", 41], " terminated\n", [["Server: ", "localhost", ":", "4003", 32, 40, "http", 41, 10], ["Request: ", "GET", 32, "/f7d1e4dd-6064-4495-9de1-368922928902", 10]] | "** (exit) exited in: :gen_server.call(:image_magick_pool, {:checkout, #Reference<0.302945953.2507669506.73455>, true}, 5000)\n    ** (EXIT) time out"], {{2023, 6, 5}, {21, 26, 40, 512}}, [erl_level: :error, conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "GET", owner: #PID<0.3296.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["f7d1e4dd-6064-4495-9de1-368922928902"], path_params: %{}, port: 4003, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "localhost:4003"}], request_path: "/f7d1e4dd-6064-4495-9de1-368922928902", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, crash_reason: {:timeout, {:gen_server, :call, [:image_magick_pool, {:checkout, #Reference<0.302945953.2507669506.73455>, true}, 5000]}}, domain: [:cowboy], error_logger: %{tag: :error}, gl: #PID<0.776.0>, pid: #PID<0.3217.0>, report_cb: #Function<0.79357776/1 in :error_logger.report_to_format>, time: 1685993200512842]}}
State: Appsignal.Error.Backend
[error] GenServer #PID<0.3359.0> terminating
** (stop) {:EXIT, {%Protocol.UndefinedError{protocol: Enumerable, value: {:gen_server, :call, [:image_magick_pool, {:checkout, #Reference<0.302945953.2507669506.73455>, true}, 5000]}, description: ""}, [{Enumerable, :impl_for!, 1, [file: 'lib/enum.ex', line: 1]}, {Enumerable, :reduce, 3, [file: 'lib/enum.ex', line: 166]}, {Enum, :map, 2, [file: 'lib/enum.ex', line: 4307]}, {Appsignal.Error, :metadata, 2, [file: 'lib/appsignal/error.ex', line: 7]}, {Appsignal.Span, :add_error, 4, [file: 'lib/appsignal/span.ex', line: 244]}, {Appsignal.Error.Backend, :set_error_data, 3, [file: 'lib/appsignal/error/backend.ex', line: 97]}, {Appsignal.Error.Backend, :handle_event, 2, [file: 'lib/appsignal/error/backend.ex', line: 30]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 802]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 784]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 526]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
Last message: {:gen_event_EXIT, Appsignal.Error.Backend, {:EXIT, {%Protocol.UndefinedError{protocol: Enumerable, value: {:gen_server, :call, [:image_magick_pool, {:checkout, #Reference<0.302945953.2507669506.73455>, true}, 5000]}, description: ""}, [{Enumerable, :impl_for!, 1, [file: 'lib/enum.ex', line: 1]}, {Enumerable, :reduce, 3, [file: 'lib/enum.ex', line: 166]}, {Enum, :map, 2, [file: 'lib/enum.ex', line: 4307]}, {Appsignal.Error, :metadata, 2, [file: 'lib/appsignal/error.ex', line: 7]}, {Appsignal.Span, :add_error, 4, [file: 'lib/appsignal/span.ex', line: 244]}, {Appsignal.Error.Backend, :set_error_data, 3, [file: 'lib/appsignal/error/backend.ex', line: 97]}, {Appsignal.Error.Backend, :handle_event, 2, [file: 'lib/appsignal/error/backend.ex', line: 30]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 802]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 784]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 526]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}}
State: Appsignal.Error.Backend
```

## To Reproduce

- {:appsignal, "~> 2.7"}
- {:poolboy, "~> 1.5"}
- Elixir 1.14
- {:phoenix, "~> 1.6.11"}

```elixir
  defp execute_command(seal_command_string) do
    # Checkout a worker, block if the pool is empty, timeout
    worker_pid = :poolboy.checkout(:image_magick_pool, true, 5_000)
    try do
      case GenServer.call(worker_pid, {:convert, seal_command_string}, :infinity) do
        {:error, message} -> raise(IMError, message)
        seal_image -> seal_image
      end
    after
      :poolboy.checkin(:image_magick_pool, worker_pid)
    end
  end
```

**Comment by jeffkreeftmeijer** [comment] 2023-06-09 08:54
Hey David,

Thanks for reporting this. I've been looking into this issue, and it seems like we're getting an error report in an unsupported format in our error backend. When it gets to producing an error, your example calls the equivalent of this:

```elixir
Exception.format_stacktrace({:gen_server, :call, [:image_magick_pool, {:checkout, self(), true}, 5000]}) 
```

Causing a result like this:

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:gen_server, :call, [:image_magick_pool, {:checkout, #PID<0.105.0>, true}, 5000]} of type Tuple
    (elixir 1.15.0-rc.1) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.15.0-rc.1) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.15.0-rc.1) lib/enum.ex:4384: Enum.map_intersperse/3
    (elixir 1.15.0-rc.1) lib/enum.ex:1794: Enum.map_join/3
    (elixir 1.15.0-rc.1) lib/exception.ex:662: Exception.format_stacktrace/1
    iex:1: (file)
```

We haven't seen this before, but even if we're getting something that isn't a stacktrace passed as one, we shouldn't crash the error handler.

Since the value passed here is a tuple, we can't extract any useful information out of it, so <https://github.com/appsignal/appsignal-elixir/commit/1fe1e14aae834c14f79dcc619c13ce05ac423646> strips the stack trace out and passes an empty list. That way, the error is still caught, although we don't have a stack trace here. We'll release a new version of the integration with this patch merged soon, so issues like this don't break the error handler in the future.

Now, the undelying reason this is happening is because this seems to be an error format the error backend isn't expecting, and one we haven't seen before.

The error backend itself has a specific lists of errors it passes through, as most of the reports coming in don't need to be registered as exceptions. We might opt for ignoring timeouts like these, as they seem like they're not really actionable, as we'd expect some other place in your app to raise an exception if this happens.

I'm looking into why this could be the case with the report you've provided, but I'm unsure if we can extract more data from this specific situation.

**Comment by jeffkreeftmeijer** [comment] 2023-06-09 12:55
Diving in a bit more, this was caused by an edge case in the error backend, where we missed this specific type of error in the :cowboy domain. Aside from the patch we discussed, where broken stack traces won't break the error backend anymore, https://github.com/appsignal/appsignal-elixir/pull/854 includes a patch to explicitly ignore all cowboy error reports.

**Closed** 2023-06-12 14:45 UTC
Labels: bug
