### ISSUE TITLE
AppSignal causes Phoenix to seg fault when a request is received on MacOS 13.6

### ISSUE THREAD

**Issue by navinpeiris** [appsignal/appsignal-elixir#892] opened 2023-09-25 04:11 UTC
Currently, AppSignal causes Phoenix to exit with `segmentation fault  mix phx.server` when it receives a request.

This started happening yesterday after installing the latest MacOS update + upgrading homebrew packages.

Setting `config :appsignal, :config, active: false` fixes the issue and Phoenix responds as expected.

## System details:

MacOS: 13.6
Xcode: 15.0
Elixir: 1.15.6 (installed through asdf)
Erlang: 26.1 (installed through asdf)
Appsignal: latest

## I've also tried:

- Fresh install of homebrew
- Elixir versions 1.15.5
- Erlang 26.0.2
- Using elixir + erlang through homebrew instead of asdf

Not sure what other information would be helpful, more than happy to provide whatever you need.

**Comment by unflxw** [comment] 2023-09-26 09:20
Hi @navinpeiris! Thank you for reporting this.

I have experienced occasional segfaults after upgrading to Erlang 26 as well, but I have not been able to consistently reproduce them. At the time, I also had not considered AppSignal to be directly related to the segfaults.

If you are aware of a setup that _consistently_ causes the segfaults to happen, that would be very useful to us. If you have such a setup, could you also check whether downgrading to Erlang 25 fixes the issue? I have a hunch that it might, and if so, this would help us narrow down the scope for the issue.

**Comment by navinpeiris** [comment] 2023-09-27 00:33
Hi @unflxw! Tried to get a sample project going that reproduces the issue, but couldn't get past `mix appsignal.install`; it seg faults as well.

This repo was created using: `mix phx.new hello --no-ecto`, and the only addition is adding `appsignal_phoenix` as a dependency: https://github.com/navinpeiris/appsignal-elxiir-issue-892

Can confirm the seg fault occurs when using Elang 25.3 as well.

The output when running `mix appsignal.install`:

<img width="1148" alt="Screenshot 2023-09-27 at 5 57 53 am" src="https://github.com/appsignal/appsignal-elixir/assets/410939/d979908a-baec-46c4-8f51-49e8b0ede8f0">

**Comment by tombruijn** [comment] 2023-10-09 12:39
I've tried to reproduce on macOS 13.6, Erlang 26.1 and Elixir 1.15.5, but no luck. Don't get it on `mix appsignal.install` or firing some requests at it. cc @jeffkreeftmeijer

**Comment by jeffkreeftmeijer** [comment] 2023-10-10 09:36
I haven't been able to reproduce this either, back on 13.x and now on 14.0.

**Comment by Teilkasko** [comment] 2023-11-07 11:22
I can reproduce the segfault error. Also my colleague @philipgiuliani sees these errors, we are each using an Intel-based Mac.

Using
macOS 13.6.1
elixir 1.15.7-otp-26(installed through rtx)
erlang 26.1.2 (installed through rtx)

I have also tried 
- using elixir + erlang installed through Homebrew
- downgrading elixir to version 1.15.0

**Comment by unflxw** [comment] 2023-11-07 12:20
Thank you for your report @Teilkasko, I will take another look at this as soon as possible.

**Comment by unflxw** [comment] 2023-11-20 16:18
Well, this is quite annoying. Trying to pick this issue back up, now I can't reproduce it myself...

@Teilkasko Are you still running into this issue? If so, could you check whether running `mix deps.clean` fixes it? I'm thinking it might be that you've updated AppSignal to a new version, but there's an old version of the AppSignal agent installed locally in your project, missing some of the NIF hooks.

**Comment by Teilkasko** [comment] 2023-11-20 16:27
@unflxw Thanks for your efforts. I am not able to work on that project/in  that specific environment this week. Will get back to you next week.

**Comment by Teilkasko** [comment] 2023-11-27 15:11
@unflxw Upgrading from v2.2.1 to 2.3.4 and cleaning the dependencies, as suggested by you, resolved the issue for me now. The segfault does not occur anymore. Thank you for your support.

**Comment by unflxw** [comment] 2023-11-27 15:21
Thank you @Teilkasko!

Since I cannot reproduce this either, I am going to tentatively close this, until further reports occur. Thank you for letting me know.

**Closed by unflxw** 2023-11-27 15:21 UTC
Labels: bug

**Comment by ian-smithers** [comment] 2023-12-05 08:20
Hi @unflxw - myself and a colleague (both on Intel Macs) are experiencing this issue.

I am on Mac OS Sonoma 14.1.2 and we are using AppSignal 2.7.3 in our project. I can reproduce this 100% of the time.
Two other colleagues whom have M1/M2 Macs, do not experience this issue.

Hope that helps! Feel free to ping with any questions - thanks!
