### ISSUE TITLE
Upgraded from 1.3.5 to 1.4.0, getting Nif and logger error

### ISSUE THREAD

**Issue by doughsay** [appsignal/appsignal-elixir#273] opened 2017-11-07 22:56 UTC
I'm deploying using docker containers and distillery, on an alpine linux base.  Appsignal has been working fine for quite a while now, but the upgrade to 1.4.0 broke.

I think the most relevant bit is here:

```
{#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<"cannot use Logger, the :logger application is not running">>},[{'Elixir.Logger.Config','__data__',0,[{file,"lib/logger/config.ex"},{line,53}]},{'Elixir.Logger',bare_log,3,[{file,"lib/logger.ex"},{line,576}]},{'Elixir.Appsignal.Nif',init,0,[{file,"lib/appsignal/nif.ex"},{line,46}]},{init,'-run_on_load_handlers/2-fun-0-',1,[]}]}
```

Looks like it's failing to log something because Logger isn't running; which is weird, because usually it is running...  But also, the only reason I see that it *would* be trying to log in this situation is to tell me that the nif is incompatible.  But it's worked so far?

Anyway, the full crash report is below in case it helps:

```
2017-11-07T22:35:15.761479315Z 2017-11-07 22:35:15 Error in process ~p on node ~p with exit value:~n~p~n
2017-11-07T22:35:15.761922615Z 			2017-11-07 22:35:15 crash_report
2017-11-07T22:35:15.762689717Z     initial_call:     pid:     registered_name:     error_info:     ancestors:     message_queue_len:     messages:     links:     dictionary:     trap_exit:     status:     heap_size:     stack_size:     reductions: 2017-11-07 22:35:15 supervisor_report
2017-11-07T22:35:15.761569353Z <0.2536.0>
2017-11-07T22:35:15.761596493Z 'noreaga@10.5.0.16'
2017-11-07T22:35:15.761833826Z {#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<"cannot use Logger, the :logger application is not running">>},[{'Elixir.Logger.Config','__data__',0,[{file,"lib/logger/config.ex"},{line,53}]},{'Elixir.Logger',bare_log,3,[{file,"lib/logger.ex"},{line,576}]},{'Elixir.Appsignal.Nif',init,0,[{file,"lib/appsignal/nif.ex"},{line,46}]},{init,'-run_on_load_handlers/2-fun-0-',1,[]}]}
2017-11-07T22:35:15.762022414Z {supervisor,kernel,['Argument__1']}
2017-11-07T22:35:15.762035236Z <0.2522.0>
2017-11-07T22:35:15.762055666Z []
2017-11-07T22:35:15.762370978Z {exit,{on_load_function_failed,'Elixir.Appsignal.Nif'},[{init,run_on_load_handlers,0,[]},{kernel,init,1,[{file,"kernel.erl"},{line,217}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2017-11-07T22:35:15.762392017Z [kernel_sup,<0.2498.0>]
2017-11-07T22:35:15.762596726Z 0
2017-11-07T22:35:15.762615369Z []
2017-11-07T22:35:15.762620583Z [<0.2499.0>]
2017-11-07T22:35:15.762623317Z []
2017-11-07T22:35:15.762625441Z true
2017-11-07T22:35:15.762631172Z running
2017-11-07T22:35:15.762633376Z 610
2017-11-07T22:35:15.762635406Z 27
2017-11-07T22:35:15.762637384Z 235
2017-11-07T22:35:15.762643134Z {local,kernel_sup}
2017-11-07T22:35:15.762794790Z start_error
2017-11-07T22:35:15.762806201Z {on_load_function_failed,'Elixir.Appsignal.Nif'}
2017-11-07T22:35:15.762993317Z [{pid,undefined},{id,kernel_safe_sup},{mfargs,{supervisor,start_link,[{local,kernel_safe_sup},kernel,safe]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]
2017-11-07T22:35:16.768307679Z     supervisor:     errorContext:     reason:     offender: 2017-11-07 22:35:16 crash_report
2017-11-07T22:35:16.768461630Z {application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}
2017-11-07T22:35:16.768526621Z <0.2497.0>
2017-11-07T22:35:16.768537816Z []
2017-11-07T22:35:16.768543637Z {exit,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Appsignal.Nif'}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2017-11-07T22:35:16.768619173Z [<0.2496.0>]
2017-11-07T22:35:16.768628768Z 1
2017-11-07T22:35:16.768639131Z [{'EXIT',<0.2498.0>,normal}]
2017-11-07T22:35:16.768645637Z [<0.2496.0>,<0.2495.0>]
2017-11-07T22:35:16.768651604Z []
2017-11-07T22:35:16.768657043Z true
2017-11-07T22:35:16.768663533Z running
2017-11-07T22:35:16.768669277Z 376
2017-11-07T22:35:16.768680964Z 27
2017-11-07T22:35:16.768684494Z 213
2017-11-07T22:35:16.769642625Z kernel
2017-11-07T22:35:16.769560286Z     initial_call:     pid:     registered_name:     error_info:     ancestors:     message_queue_len:     messages:     links:     dictionary:     trap_exit:     status:     heap_size:     stack_size:     reductions: 2017-11-07 22:35:16 std_info
2017-11-07T22:35:16.770419934Z {{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Appsignal.Nif'}}},{kernel,start,[normal,[]]}}
2017-11-07T22:35:16.770457854Z permanent
2017-11-07T22:35:17.271584900Z {"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Appsignal.Nif'}}},{kernel,start,[normal,[]]}}}"}
2017-11-07T22:35:17.271784149Z     application:     exited:     type: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Appsignal.Nif'}}},{kernel,start,[no
2017-11-07T22:35:17.275109211Z
2017-11-07T22:35:19.286544783Z Crash dump is being written to: erl_crash.dump...done
```

**Comment by jeffkreeftmeijer** [comment] 2017-11-08 11:09
Hey @doughsay, :wave:

Thanks for reporting this! We're able to reproduce this on the [alpine](https://github.com/jeffkreeftmeijer/appsignal-phoenix-example/tree/alpine) branch in our example application. The Dockerfile in there is based on @joshuataylor's (who had the same issue in #272).

Like Chris said, this issue is two-fold. There's an issue loading the `:logger` application, which crashes the app when an error message is logged while trying to load the C extension. The message itself is as follows:

```
'Failed to load NIF library: \'Error loading shared library libgcc_s.so.1: No such file or directory (needed by /app/_build/prod/rel/appsignal_phoenix_example/lib/appsignal-1.4.0/priv/appsignal_extension.so)\''
```

Which means we failed to detect musl during compilation, resulting in a GNU build which doesn't run on Alpine. After some more digging, we found that bitwalker/alpine-elixir reports `'x86_64-unknown-linux-gnu'` as the system architecture:

```
$ docker run --rm -it bitwalker/alpine-elixir:1.5.2 iex
Erlang/OTP 20 [erts-9.1.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :erlang.system_info(:system_architecture)
'x86_64-unknown-linux-gnu'
```

Chris, could you send us your Dockerfile (in this issue, or via support@appsignal.com), so we can do some more research?

We've updated [our documentation for Alpine](https://docs.appsignal.com/support/operating-systems.html#alpine-linux) to include the `APPSIGNAL_BUILD_FOR_MUSL` environment variable you can use to force a musl build even if `:erlang.system_info(:system_architecture)` doesn't recognise your architecture correctly. Could you try setting it and let us know if that makes your app start again?

We'll update this issue as soon as we know more.

**Comment by tombruijn** [comment] 2017-11-08 12:31
Submitted a fix to the bitwalker/erlang docker image here: https://github.com/bitwalker/alpine-erlang/pull/16

Won't retroactively fix older bitwalker/erlang and bitwalker/elixir images, but would help prevent target mismatches for newer images.

We should probably add this problem to the [Known issues](https://docs.appsignal.com/support/known-issues.html) page.

**Comment by tombruijn** [comment] 2017-11-08 14:21
Created a separate known issue page for this particular issue: https://docs.appsignal.com/support/known-issues/alpine-linux-ruby-gem-2-4-elixir-package-1-4-upgrade-problems.html

**Comment by doughsay** [comment] 2017-11-09 05:13
Thanks for jumping on this so quickly!  I am indeed using `FROM bitwalker/alpine-elixir:1.5.2` in my Dockerfile, so this makes sense.  I will try using the new env var, or update the base image.  Thanks!

**Comment by tombruijn** [comment] 2017-11-09 10:15
The installation issue with detecting the wrong architecture is fixed. We'll keep this issue to track the problem with the logger not being started when this error occurs. assigned to @jeffkreeftmeijer

**Closed** 2017-11-13 12:10 UTC
Labels: bug, support

**Comment by jeffkreeftmeijer** [comment] 2017-11-13 12:22
To recap; the problem was caused by bitwalker/alpine-elixir:1.5.2 misreporting the system architecture, which caused the AppSignal integration to download the wrong build of the agent. The log message we tried to produce came from the Nif's on_load function, which is run before the `:logger` application was started. 

The first part was fixed by Tom in https://github.com/bitwalker/alpine-erlang/pull/16 by setting the correct system architecture, and #275 fixed calling to the `:logger` before it was instantiated.

We're closing this issue, but feel free to reopen it if you run into this issue and the workaround on our [documentation page](https://docs.appsignal.com/support/known-issues/alpine-linux-ruby-gem-2-4-elixir-package-1-4-upgrade-problems.html) about this doesn't fix the issue.

**Comment by lessless** [comment] 2018-02-01 17:33
Bumped into this on Ubuntu 16.04 LTS

```
018-02-01 12:31:49 Error in process ~p on node ~p with exit value:~n~p~n
	<0.2259.0>
	'flowmail_web@127.0.0.1'
	{#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<"cannot use Logger, the :logger application is not running">>},[{'Elixir.Logger.Config','__data__',0,[{file,"lib/logger/config.ex"},{line,53}]},{'Elixir.Logger',bare_log,3,[{file,"lib/logger.ex"},{line,612}]},{'Elixir.Appsignal.Nif',init,0,[{file,"lib/appsignal/nif.ex"},{line,46}]},{init,'-run_on_load_handlers/2-fun-0-',1,[]}]}
2018-02-01 12:31:49 crash_report
    initial_call: {supervisor,kernel,['Argument__1']}
    pid: <0.2256.0>
    registered_name: []
    error_info: {exit,{on_load_function_failed,'Elixir.Appsignal.Nif'},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,352}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [kernel_sup,<0.2234.0>]
    messages: []
    links: [<0.2235.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 117
2018-02-01 12:31:49 supervisor_report
    supervisor: {local,kernel_sup}
    errorContext: start_error
    reason: {on_load_function_failed,'Elixir.Appsignal.Nif'}
    offender: [{pid,undefined},{id,kernel_safe_sup},{mfargs,{supervisor,start_link,[{local,kernel_safe_sup},kernel,safe]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]
2018-02-01 12:31:50 crash_report
    initial_call: {application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}
    pid: <0.2233.0>
    registered_name: []
    error_info: {exit,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Appsignal.Nif'}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.2232.0>]
    messages: [{'EXIT',<0.2234.0>,normal}]
    links: [<0.2232.0>,<0.2231.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 152
2018-02-01 12:31:50 std_info
    application: kernel
    exited: {{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Appsignal.Nif'}}},{kernel,start,[normal,[]]}}
    type: permanent
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Appsignal.Nif'}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Appsignal.Nif'}}},{kernel,start,[no
```

Client version is 1.4.7

**Comment by lessless** [comment] 2018-02-02 14:47
Looks like was due to caching on the CD server

**Comment by tombruijn** [comment] 2018-02-02 15:06
Ah that's good to hear! Did you see my message in our support app? And did `mix deps.clean appsignal` help in the end?

**Comment by joshuataylor** [comment] 2018-02-02 15:27
This is why we don't cache on CI/CD and do a fresh build.

Also `mix deps.clean appsignal` hasn't worked for me when I'm developing locally, I see this a few times a day when I'm in one of my umbrella apps, then change to another that uses phoenix/absinthe and it fails.

**Comment by jeffkreeftmeijer** [comment] 2018-02-07 11:10
Hey @joshuataylor,

Could you explain a little more about your setup? Although two apps can't run simultaneously on one machine, switching back and forth should work without having to recompile the dependency each time, as they're built in different directories. Also, does any of your apps still run a version lower than 1.4.3? The logger issue should be fixed in newer versions.

Thanks!
